algoritmo "exercicio11"
// Função :
// Autor :
// Data : 29/08/2018
// Seção de Declarações 
var
cm,m,dm,mm: real
inicio
escreval ("digite o número (cm):")
leia (cm)
m <- cm/100
escreval ("o número mencionado em cm equivale a:", m, " metros")
dm <- cm/10
escreval ("o número mencionado em cm equivale a:", dm, " decímetros")
mm <- cm * 10
escreval ("o número mencionado em cm equivale a:", mm, " milímetros")
fimalgoritmo
