algoritmo "exercicio13"
// Função :
// Autor :
// Data : 29/08/2018
// Seção de Declarações 
var
A,B,C,X1,X2: real
inicio
escreval ("digite um valor para A:")
leia (A)
escreval ("digite um valor para B")
leia (B)
escreval ("digite um valor para C")
leia (C)
X1 <- (-b+raizq(b^2-4*A*C))/2*A
X2 <- (-b-raizq(b^2-4*A*C))/2*A
escreval ("o valor de X1 é:", X1)
escreval ("o valor de X2 é:", X2)
fimalgoritmo
